# Site settings
title: Multi-Agent Programming Contest
url: "https://multiagentcontest.org"
baseurl: ""

# Build settings
incremental: false
markdown: kramdown

# Plugins
gems:
 - jekyll-redirect-from
