# Site settings
title: Multi-Agent Programming Contest
url: "https://www.multiagentcontest.org"
baseurl: ""

# Build settings
incremental: false
markdown: kramdown

# Plugins
plugins:
 - jekyll-redirect-from
